resources:
  repositories:
    - repository: ci-perl-helpers
      type: github
      name: houseabsolute/ci-perl-helpers
      endpoint: houseabsolute/ci-perl-helpers

stages:
  - template: templates/helpers/build.yml@ci-perl-helpers
  - template: templates/helpers/linux.yml@ci-perl-helpers
    parameters:
      test_xt: true
      use_default_perls: true
  - template: templates/helpers/macos.yml@ci-perl-helpers
    parameters:
      use_default_perls: true
  - template: templates/helpers/windows.yml@ci-perl-helpers
    parameters:
      use_default_perls: true
