---
# https://github.com/codecov/example-perl

machine:
  environment:
    PATH: ~/perl5/bin:$PATH
    AUTOMATED_TESTING: 1
    AUTHOR_TESTING: 1

dependencies:
  pre:
    - curl -L https://cpanmin.us | perl - App::cpanminus
    - cpanm --local-lib=~/perl5 local::lib && echo "eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)" >> ~/.bashrc
    - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
    - cpanm -iqn Test::Most Test::Needs

test:
  override:
    - perl Makefile.PL
    - make
    - make test
    - cover -test

  post:
    - cover -report codecov
