---
# see https://github.com/FGasper/perl-github-action-tips

name: Test Code on Alpine Linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: alpine

    steps:
      - name: Install Dependencies
        continue-on-error: true
        run: |
          apk update
          apk upgrade
          apk add perl perl-app-cpanminus make gzip git
          perl -V
          cpanm -ivn ExtUtils::MakeMaker File::Spec
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git
          cd /__w/CGI-Info/CGI-Info
          find .
          cpanm -iv --installdeps --notest .
      - name: Make module
        run: |
          find ~ -name build.log | xargs cat
          ls -l
          pwd
          perl Makefile.PL
          make
      - name: Run Tests
        run: prove -wlvmb t
