---
# see https://github.com/FGasper/perl-github-action-tips

name: Test Code on Alpine Linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: alpine

    steps:
      - name: Install Dependencies
        continue-on-error: true
        run: |
          apk update
          apk upgrade
          apk add perl perl-app-cpanminus make gzip git
          perl -V
          cpanm -ivn ExtUtils::MakeMaker File::Spec
          cd $GITHUB_WORKSPACE
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git
          cd CGI-Info
          cpanm -iv --installdeps --notest .
      - name: Make module
        run: |
          # find ~ -name build.log | xargs cat
          cd $GITHUB_WORKSPACE/CGI-Info
          perl Makefile.PL
          make
      - name: Run Tests
        run: |
          cd $GITHUB_WORKSPACE/CGI-Info
          prove -wlvmb t
