---
# See https://github.com/actions/virtual-environments
# and https://github.com/shogo82148/actions-setup-perl/tree/v1.31.3

name: Test Code on Windows using Strawberry Perl
permissions:
  contents: read
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        perl: ['5.40', '5.38', '5.32', '5.30', '5.24']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: codecov/codecov-action@v5
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: strawberry
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn --skip-satisfied File::Spec ExtUtils::MakeMaker Test::Harness
          cpanm -iqn --skip-satisfied Test::Script Test::Taint Test::Carp Test::Compile Test::Pod::Coverage LWP::UserAgent
          cpanm -iqn --skip-satisfied --installdeps --notest .
      - name: Run Tests
        run: prove -l t
        env:
          AUTOMATED_TESTING: 1
