---
# see https://github.com/FGasper/perl-github-action-tips
# and https://github.com/actions/virtual-environments

name: Test Code on Ubuntu
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
        perl-version: ['5.36', '5.34', '5.32', '5.30', '5.28', '5.22', '5.20', '5.18', '5.16', '5.14', '5.12', '5.10']
    name: Perl ${{ matrix.perl-version }} on ${{ matrix.os }}

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@main
        with:
          submodules: recursive
      - uses: codecov/codecov-action@v3
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn File::Spec ExtUtils::MakeMaker Devel::Cover::Report::Codecov Test::Harness
          cpanm -iqn --skip-satisfied Test::Script Test::Portability::Files Test::Taint Test::Carp Test::Compile Test::Pod::Coverage LWP::UserAgent
          cpanm -iqn --skip-satisfied --installdeps --notest .
      - name: Run Tests
        run: |
          cover -test
          cover -report codecov
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }}
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
