---
# See https://github.com/actions/virtual-environments

name: Test Code on Ubuntu
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
        perl: ['5.34', '5.32', '5.30', '5.28']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: codecov/codecov-action@v2
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn --skip-satisfied File::Spec ExtUtils::MakeMaker Devel::Cover::Report::Codecov Test::Harness
          cpanm -iqn --skip-satisfied Test::Script Test::Portability::Files Test::Taint Test::Carp Test::Compile Test::Pod::Coverage LWP::UserAgent
          cpanm -iqn --skip-satisfied --installdeps --notest .
      - name: Run Tests
        run: |
          cover -test
          cover -report codecov
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t fe086bb5-1d90-491c-b5b4-48cbf5bedfb5
        shell: bash
        env:
          AUTHOR_TESTING: 1
          CODECOV_TOKEN: fe086bb5-1d90-491c-b5b4-48cbf5bedfb5
